[package]
name = "ownership-dag"
version = "0.1.0"
edition = "2021"

[[example]]
name = "refcell-example"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
